version: "2"

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    restart: always

  thuglet:
    build: thugd
    image: thugd
    hostname: thuglet
    network_mode: "host"
    environment:
    - RMQ_PORT=5672
    - MGT_PORT=15672
    - MDB_PORT=27017
    restart: always
